using System;
using BigBoys.Execution;
using BigBoys.Lua;

namespace BigBoys.Context
{
    public partial interface IContext
    {
        void IncAcquisitionRangeMod(float delta, IUnit target);
        void IncBaseAttackDamage(float delta, IUnit target);
        void IncFlatArmorMod(float delta, IUnit target);
        void IncFlatArmorPenetrationMod(float delta, IUnit target);
        void IncFlatAttackRangeMod(float delta, IUnit target);
        void IncFlatBubbleRadiusMod(float delta, IUnit target);
        void IncFlatCastRangeMod(float delta, IUnit target);
        void IncFlatCooldownMod(float delta, IUnit target);
        void IncFlatCritChanceMod(float delta, IUnit target);
        void IncFlatCritDamageMod(float delta, IUnit target);
        void IncFlatDodgeMod(float delta, IUnit target);
        void IncFlatGoldPer10Mod(float delta, IUnit target);
        void IncFlatHPPoolMod(float delta, IUnit target);
        void IncFlatHPRegenMod(float delta, IUnit target);
        void IncFlatMagicDamageMod(float delta, IUnit target);
        void IncFlatMagicPenetrationMod(float delta, IUnit target);
        void IncFlatMagicReduction(float delta, IUnit target);
        void IncFlatMissChanceMod(float delta, IUnit target);
        void IncFlatMovementSpeedMod(float delta, IUnit target);
        void IncFlatPhysicalDamageMod(float delta, IUnit target);
        void IncFlatPhysicalReduction(float delta, IUnit target);
        void IncFlatSpellBlockMod(float delta, IUnit target);
        void IncHealth(float delta, IUnit target);
        void IncMana(float delta, IUnit target);
        void IncMoveSpeedFloorMod(float delta, IUnit target);
        void IncPercentArmorMod(float delta, IUnit target);
        void IncPercentArmorPenetrationMod(float delta, IUnit target);
        void IncPercentAttackRangeMod(float delta, IUnit target);
        void IncPercentAttackSpeedMod(float delta, IUnit target);
        void IncPercentBubbleRadiusMod(float delta, IUnit target);
        void IncPercentCastRangeMod(float delta, IUnit target);
        void IncPercentCooldownMod(float delta, IUnit target);
        void IncPercentCritDamageMod(float delta, IUnit target);
        void IncPercentEXPBonus(float delta, IUnit target);
        void IncPercentGoldLostOnDeathMod(float delta, IUnit target);
        void IncPercentHPPoolMod(float delta, IUnit target);
        void IncPercentHPRegenMod(float delta, IUnit target);
        void IncPercentHardnessMod(float delta, IUnit target);
        void IncPercentHealingAmountMod(float delta, IUnit target);
        void IncPercentLifeStealMod(float delta, IUnit target);
        void IncPercentMagicDamageMod(float delta, IUnit target);
        void IncPercentMagicPenetrationMod(float delta, IUnit target);
        void IncPercentMagicReduction(float delta, IUnit target);
        void IncPercentMovementSpeedMod(float delta, IUnit target);
        void IncPercentMultiplicativeAttackSpeedMod(float delta, IUnit target);
        void IncPercentMultiplicativeMovementSpeedMod(float delta, IUnit target);
        void IncPercentPhysicalDamageMod(float delta, IUnit target);
        void IncPercentPhysicalReduction(float delta, IUnit target);
        void IncPercentRespawnTimeMod(float delta, IUnit target);
        void IncPercentSpellBlockMod(float delta, IUnit target);
        void IncPercentSpellVampMod(float delta, IUnit target);
        void IncPermanentAcquisitionRangeMod(float delta, IUnit target);
        void IncPermanentBaseAttackDamage(float delta, IUnit target);
        void IncPermanentFlatArmorMod(float delta, IUnit target);
        void IncPermanentFlatArmorPenetrationMod(float delta, IUnit target);
        void IncPermanentFlatAttackRangeMod(float delta, IUnit target);
        void IncPermanentFlatBubbleRadiusMod(float delta, IUnit target);
        void IncPermanentFlatCastRangeMod(float delta, IUnit target);
        void IncPermanentFlatCooldownMod(float delta, IUnit target);
        void IncPermanentFlatCritChanceMod(float delta, IUnit target);
        void IncPermanentFlatCritDamageMod(float delta, IUnit target);
        void IncPermanentFlatGoldPer10Mod(float delta, IUnit target);
        void IncPermanentFlatHPPoolMod(float delta, IUnit target);
        void IncPermanentFlatHPRegenMod(float delta, IUnit target);
        void IncPermanentFlatMagicDamageMod(float delta, IUnit target);
        void IncPermanentFlatMagicPenetrationMod(float delta, IUnit target);
        void IncPermanentFlatMagicReduction(float delta, IUnit target);
        void IncPermanentFlatMovementSpeedMod(float delta, IUnit target);
        void IncPermanentFlatPhysicalDamageMod(float delta, IUnit target);
        void IncPermanentFlatPhysicalReduction(float delta, IUnit target);
        void IncPermanentFlatSpellBlockMod(float delta, IUnit target);
        void IncPermanentPercentAttackRangeMod(float delta, IUnit target);
        void IncPermanentPercentAttackSpeedMod(float delta, IUnit target);
        void IncPermanentPercentBubbleRadiusMod(float delta, IUnit target);
        void IncPermanentPercentCastRangeMod(float delta, IUnit target);
        void IncPermanentPercentCooldownMod(float delta, IUnit target);
        void IncPermanentPercentCritDamageMod(float delta, IUnit target);
        void IncPermanentPercentEXPBonus(float delta, IUnit target);
        void IncPermanentPercentGoldLostOnDeathMod(float delta, IUnit target);
        void IncPermanentPercentHPPoolMod(float delta, IUnit target);
        void IncPermanentPercentHPRegenMod(float delta, IUnit target);
        void IncPermanentPercentHardnessMod(float delta, IUnit target);
        void IncPermanentPercentHealingAmountMod(float delta, IUnit target);
        void IncPermanentPercentLifeStealMod(float delta, IUnit target);
        void IncPermanentPercentMagicDamageMod(float delta, IUnit target);
        void IncPermanentPercentMagicReduction(float delta, IUnit target);
        void IncPermanentPercentMovementSpeedMod(float delta, IUnit target);
        void IncPermanentPercentPhysicalDamageMod(float delta, IUnit target);
        void IncPermanentPercentPhysicalReduction(float delta, IUnit target);
        void IncPermanentPercentRespawnTimeMod(float delta, IUnit target);
        void IncPermanentPercentSpellBlockMod(float delta, IUnit target);
        void IncPermanentPercentSpellVampMod(float delta, IUnit target);
    }
}
